@startuml

autonumber

actor "Tourist" as tourist
box "Application Server" #LightBlue
    participant ":AdminController" as controller
    participant ":AdminCommandHandler" as handler
    participant ":AccountRepository" as accRepo
    participant ":EventPublisher" as eventPub
    participant ":Admin" as act
end box

tourist -> controller : promote(request)
activate controller

controller -> handler : promote(command)
activate handler

handler -> accRepo : getAdminById(accountId)
activate accRepo
handler <-- accRepo : Admin
deactivate accRepo

handler -> act : promote(account, roles)
activate act
act -> act : apply(AccountPromoted)
handler <-- act : true
deactivate act

handler -> accRepo : promote(accountId, roles)
handler -> eventPub : publish(events)

deactivate handler

controller --> tourist : HTTP 204
deactivate controller

@enduml