@startuml
autonumber

actor "Tourist, Tour operator" as user
box "Application Server" #LightBlue
    participant ":AccountController" as controller
    participant ":TourQueryHandler" as handler
    participant ":AccountRepository" as accRepo
    participant ":TourProjection" as projection
end box

user -> controller : privateSearch(request)
activate controller

controller -> handler : privateSearch(privateQuery)
activate handler

handler -> accRepo : getTourOperatorById(accountId)
activate accRepo
handler <-- accRepo : TourOperator
deactivate accRepo

handler -> projection : privateSearch(privateQuery)
activate projection
handler <-- projection : List<SummarizedPrivateTour>
deactivate projection

handler --> controller : List<SummarizedPrivateTour>
deactivate handler

controller --> user : HTTP 200 + JSON list
deactivate controller

@enduml