@startuml

autonumber

actor "Tour operator" as tourist
box "Application Server" #LightBlue
    participant ":TourController" as controller
    participant ":TourCommandHandler" as handler
    participant ":AccountRepository" as accRepo
    participant ":TourRepository" as tourRepo
    participant ":TourOperator" as tourOp
end box

tourist -> controller : unpublish(request)
activate controller

controller -> handler : unpublish(command)
activate handler

handler -> accRepo : getTourOperatorById(accountId)
activate accRepo
handler <-- accRepo : TourOperator
deactivate accRepo
handler -> tourRepo : getScheduleById(tourId)
activate tourRepo
handler <-- tourRepo : TourSchedule
deactivate tourRepo

handler -> tourOp : unpublishTour(tour)
activate tourOp
tourOp -> tourOp : hasHosted(tour)
tourOp -> tourOp : hasPublished(tour)
tourOp -> tourOp : !hasActiveRegistration(tour)
handler <-- tourOp : true
deactivate tourOp

handler -> tourRepo : unpublish(tourId)

deactivate handler

controller --> tourist : HTTP 204
deactivate controller

@enduml