@startuml

autonumber

actor "Tourist" as tourist
box "Application Server" #LightBlue
    participant ":OrderController" as controller
    participant ":OrderCommandHandler" as handler
    participant ":AccountRepository" as accRepo
    participant ":TourRepository" as tourRepo
    participant ":PaymentRepository" as payRepo
    participant ":OrderRepository" as ordRepo
    participant ":EventPublisher" as publisher
    participant ":EncryptionService" as encrypt
    participant ":Tourist" as touristAcc
end box

tourist -> controller : getQr(request)
activate controller

controller -> handler : getQr(command)
activate handler

handler -> accRepo : getTouristById(accountId)
activate accRepo
handler <-- accRepo : Tourist
deactivate accRepo
handler -> tourRepo : getScheduleById(tourId)
activate tourRepo
handler <-- tourRepo : TourSchedule
deactivate tourRepo

handler -> accRepo : getWallet(tourOperatorId) (from TourSchedule)
activate accRepo
handler <-- accRepo : BankWallet
deactivate accRepo
handler -> tourRepo : getPriceById(priceTableId)
activate tourRepo
handler <-- tourRepo : PriceTable
deactivate tourRepo

handler -> touristAcc : reserveTour(tour, priceTable, wallet, request)
activate touristAcc
touristAcc -> touristAcc : isValid(representative)
touristAcc -> touristAcc : isBookable(tour, representative, tourists) (isOwned, isPublished, isOpen, isNotFull)
touristAcc -> touristAcc : isVerified(wallet)

touristAcc -> touristAcc : calculatePrice(priceTable, tourists)
touristAcc -> touristAcc : createOrder()
handler <-- touristAcc : Order
deactivate touristAcc

handler -> ordRepo : reserve(order)

handler -> encrypt : hashSignature(orderId, amount) (using HMAC-SHA256)
handler -> payRepo : getQr(bankBin, accountNumber, amount, notifyUrl, orderId, signature, idempotencyKey) (idempotency key created from operationName + orderId)
activate payRepo
handler <-- payRepo : qr
deactivate payRepo

controller <-- handler : qr
deactivate handler

controller --> tourist : HTTP 201 + qrString
deactivate controller

@enduml