@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant ":ChangeTitleUsecase" as U
participant "article:Article" as A
participant ":ArticleRepository" as R

[o-> U: execute
activate U

U -> R: getById
activate R
create A
R -> A: rehydrate
deactivate R

alt article not null

U -> A: changeTitle
activate A
deactivate A

U -> R: save
activate R
deactivate R

end

@enduml