@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant Client
participant System
participant Database

Client -> System: create article metadata
activate System

System -> Database: save article metadata
activate Database
deactivate Database

System -> Database: save session token
activate Database
deactivate Database

deactivate System

Client -> System: upload cover image
activate System

System -> Database: upload cover image
activate Database
deactivate Database

System -> Database: invalidate session token
activate Database
deactivate Database

deactivate System
@enduml