@startuml

|Admin|
start
:(1) Provide the reason of banishment;

|System|
:(2) Save the account status;
:(3) Inform the admin and the tourist about the banishment;

|Admin|
:(4) Review the result;
stop

@enduml
