@startuml

|Tour operator|
start
repeat :(1) Agree with tour cancellation;

|System|
backward :(2a1) Inform about the status;
repeat while ((2) Validate the tour status) is (fails)
:(3) Remove the tour from database;
:(4) Inform about the successful removal;

|Tour operator|
:(5) Review the result;

stop

@enduml
