@startuml

|Admin|
start
:(1) Provide the reason of promotion;

|System|
:(2) Save the account status;
:(3) Inform the admin and the account owner about the addition;

|Admin|
:(4) Review the result;
stop

@enduml
