@startuml

|Tour operator|
start
repeat :(1) Agree with removal;

|System|
backward :(2a1) Inform about the status;
repeat while ((2) Validate the price table status) is (fails)
:(3) Remove the price table;
:(4) Return the price tables list;

|Tour operator|
:(5) Review the result;

stop

@enduml
