@startuml

|Tour operator|
start
repeat :(1) Provide required information for departure;

|System|
backward :(2a1) Inform about the mistake;
repeat while ((2) Validate the information) is (fails)
:(3) Save the departure;
:(4) Return the departures list;

|Tour operator|
:(5) Review the result;

stop

@enduml
