@startuml
'https://plantuml.com/deployment-diagram

node "Client" {
    artifact browser
}
node "Server" {
    artifact application
}
node "Database"

"Client" -- "Server": http
"Server" -- "Database": jdbc
@enduml