@startuml
left to right direction
rectangle "Tourism promoting & Tour booking"{
    usecase "Read article" as UC1
    usecase "Book tour" as UC2
    usecase "Log in" as UC3
    usecase "Cancel booked order" as UC4
    usecase "Manage articles" as UC5
    usecase "Manage tours" as UC6
    usecase "View tour participants" as UC7
    usecase "Apply for role" as UC8
    usecase "Manage accounts" as UC9
    usecase "Rate tour" as UC10
    usecase "Report article" as UC11
    usecase "Handle reports" as UC12
    usecase "View statistics" as UC13
}
actor "Tourist" as t
actor "Tour operator" as to
actor "Editor" as e
actor "Admin" as a

to -|> t
e -|> t

t --- UC1
t --- UC2
t --- UC3
t --- UC4
t --- UC8
t --- UC10
t --- UC11

to --- UC6
to --- UC7
to --- UC13

e --- UC5
e --- UC13

a --- UC9
a --- UC12
a --- UC13
@enduml