spring:
  application:
    name: tourism-article-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
  data:
    mongo:
      uri: mongodb://localhost:27017
      database: resource_management
  servlet:
    multipart:
      enabled: false